####################################### Training mode configurations ###############################################

# General Information
nr: 320
nt: 3
osmpl_fact: 2
nspokes_array: [50, 36] # np.array([503, 251, 75, 50, 36]) # 
noise_std_list: [0.5, 0.2] # [1.0, 0.8, 0.5, 0.2, 0.1, 0.05] # [0.8, 0.5, 0.2, 0.1, 0.05, 0.01, 0.005] # 
nbootstrap: 10 # 100 # 
device: 'cuda'
