####################################### Testing mode configurations ###############################################

# General
info:
  project_name: Debug_Test
  project_description: Developing Code
  read_project_name: Debug
# Paths
paths:
  dataset: data/
  read: experiments/
  save: experiments/

# Parameters configurations for testing the framework
test_params:
  # Dataset specific
  dataset:
    file_name: dce_perfusion_data.npz
    build_dataset_flag: True
    SNR_ctc: 15
    img_dim: [120, 120]
    crop_dim: [60, 60]
    eta_bkg_ref: [0.001667, 0.1, 0.01]
  # Network specific
  load_unet: unet_load
  # Fermi Operator
  osamp: 20
  pre_scale_factor: 10
  # General
  ntest: ['Pat4']
  mode: 'testing' # 'pre_training' 'fine_tuning'
  nsamp: 100
  calib_nsamp: 100
  clean_outliers: False
  morph_flag: False
  is_erosion_not_dilate: False
  # Backend device
  device: 'cuda'
