####################################### Training mode configurations ###############################################

# General Information
info:
  project_name: Debug
  project_description: Developing Code

# Directory paths
paths:
  dataset: data/
  save: experiments/

# Parameters configurations for training the framework
train_params:
  # Dataset specific
  dataset:
    file_name: dce_perfusion_data.npz
    build_dataset_flag: False
    SNR_ctc: 15
    img_dim: [120, 120]
    crop_dim: [60, 60]
    eta_bkg_ref: [0.001667, 0.1, 0.01]
  # Network specific
  network:
    # Architecture
    ncin: 2
    nfilters: 16
    nstage: 3
    nconv_stage: 2
    ncout: 12
    learn_lambda: True
    dropout: 0.0
    # Data-consistency configurations
    osamp: 5
    max_iter_lbfgs: 10000
    max_eval_lbfgs: 10000
    # Check-pointing
    train_from_ckpt: False
    load_unet: unet_load
    backprop_ckpt: 0
  # Optimizer configurations
  optimizer:
    unet_lr: 10.e-5
    unet_wd: 10.e-7
  # General
  ntrain: ['Pat0', 'Pat1', 'Pat2']
  nval: ['Pat3']
  ntest: ['Pat4']
  nepochs: 2000
  val_step_size: 500
  mb: 1
  ssup_split: 0.3
  mode: 'fine_tuning' # 'pre_training' 'fine_tuning'
  # Fermi Operator
  osamp: 5
  pre_scale_factor: 10
  # Backend device
  device: 'cuda'
  # Cross validation
  cross_val_flag: False
  cross_val_k: 2
  cross_val_fold: 1
  # Augment training dataset
  aug_dataset_flag: False # True
